config/routes.rb
Deepvision::Application.routes.draw do

  root 'dashboard#index'

  mount Longview::API => "/endpoint"

  get 'hosts/:id/overview' => 'hosts#overview', as: :overview
  get 'hosts/:id/network' => 'hosts#network', as: :network
  get 'hosts/:id/disks' => 'hosts#disks', as: :disks
  get 'hosts/:id/processes' => 'hosts#processes', as: :processes
  get 'hosts/:id/system' => 'hosts#system', as: :system
  get 'hosts/:id/settings' => 'hosts#settings', as: :settings
  post 'hosts/:id/settings' => 'hosts#settings', as: :settings_save

  get 'hosts/add' => 'hosts#add', as: :add_host
  post 'hosts/add' => 'hosts#do_add', as: :do_add_host

  

end

app/models/host.rb
class Host
  include ActiveModel::Validations
  include ActiveModel::Serialization
  include ActiveModel::AttributeMethods

  @r = LovelyRethink.db

  define_attribute_methods :id, :name, :account_id

  validates_presence_of :id
  validates_presence_of :name

  def self.key_valid_and_active?(apikey, host = false)
    
    if !host
      host = Host.get_by_id(apikey)
    end

    if !host.nil? && host["active"].to_i == 1
      return true
    end
    false
  end

  def save
    # find the existing one and update instead if exists
  end

  def self.get_by_id(id)
    @r.table('hosts').get(id).run(LovelyRethink.connection.raw)
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController

  before_filter :load_host_and_instant, except: [:add, :do_add]
  before_filter :get_date_range, except: [:add, :do_add, :processes]


  def add
    @add_host = true
    @api_key_original = SecureRandom.uuid().upcase
    api_key_array = @api_key_original.split("-")
    api_key_array[3] = api_key_array[3] + api_key_array[4]
    api_key_array.delete_at 4
    @api_key = api_key_array.join "-"
  end

  def do_add
    if !params[:host].nil?
      host_params = params.require(:host).permit(:name, :active, :interval, :id)
      @r = LovelyRethink.db
      @rr = RethinkDB::RQL.new
      @r.table('hosts').insert(host_params).run(LovelyRethink.connection.raw)
    end
    redirect_to root_path
  end


  def overview
    @longterm_stats = Longterm.get_host_overview_stats(params[:id], session[:range_obj], 0.minutes, @range)
    @overview_series = Graph.get_overview_series(@longterm_stats)

    gon.cpu_series = @overview_series["CPU.total.usage"]
    gon.disk_series = @overview_series["Disk./dev/dm-0.reads"]
    gon.load_series = @overview_series["Load"]
    gon.memory_used_series = @overview_series["Memory.real.used"]
    gon.memory_cache_series = @overview_series["Memory.real.cache"]
    gon.memory_buffers_series = @overview_series["Memory.real.buffers"]
    gon.memory_swap_series = @overview_series["Memory.swap.used"]
    gon.network_in_series = @overview_series["Network.Interface.total.rx_Bps"]
    gon.network_out_series = @overview_series["Network.Interface.total.tx_Bps"]
    gon.disk_reads_series = @overview_series["Disk.total.reads_ps"]
    gon.disk_writes_series = @overview_series["Disk.total.writes_ps"]
  end

  def network
    unless @instant.nil?
      @network_interfaces = Longterm.get_host_network_interfaces params[:id]
      @network_stats = Longterm.get_host_network_stats(params[:id], @network_interfaces, session[:range_obj], 0.minutes, @range)

      @network_series = Graph.get_network_series(@network_stats)
      gon.network_interfaces = @network_interfaces
      gon.network_series = @network_series
    end
  end

  def disks
    unless @instant.nil?
      @disks = Longterm.get_host_disks(params[:id])
      @disk_stats = Longterm.get_host_disk_stats(params[:id], @disks, session[:range_obj], 0.minutes, @range)

      @disk_series = Graph.get_disk_series(@disk_stats)
      gon.dev_disks = @disks
      gon.dev_disk_series = @disk_series
    end
  end

  def processes
    @longterm = Longterm.get_last_entry_by_apikey(params[:id]).first

    @processes = @longterm.select {|key, value| key =~ /^Processes\..*\..*\.count$/ } unless @longterm.nil?
  end

  def system
    @longterm = Longterm.get_last_entry_by_apikey(params[:id]).first
  end

  def settings
    if !params[:host].nil?
      host_params = params.require(:host).permit(:name, :active, :interval)
      @r = LovelyRethink.db
      @rr = RethinkDB::RQL.new
      @r.table('hosts').get(params[:id]).update(host_params).run(LovelyRethink.connection.raw)
      load_host_and_instant
    end
  end

  protected

  def load_longterm_stats(attributes = nil)
    Longterm.get_range_by_apikey(params[:id], session[:range_obj], 0.minutes, attributes).to_a
  end

  def load_host_and_instant
    @host = Host.get_by_id(params[:id])
    @instant = Instant.get_by_id(params[:id])
  end

  def get_date_range
    @range_obj = 30.minutes
    @range = 1
    if !params[:r].nil?
      case params[:r].to_i
      when 5
        @range_obj = 1.year
        @range = 5
      when 4
        @range_obj = 1.month
        @range = 4
      when 3
        @range_obj = 7.days
        @range = 3
      when 2
        @range_obj = 24.hours
        @range = 2
      else
        @range_obj = 30.minutes
        1
      end
      redirect_to controller: params[:controller], action: params[:action], id: params[:id]
    elsif !session[:range].nil?
      @range = session[:range]
      @range_obj = session[:range_obj]
    end
    session[:range] = @range
    session[:range_obj] = @range_obj
    @range
  end

end

app/helpers/hosts_helper.rb
module HostsHelper

end

app/views/hosts/_waiting.html.erb
<h4>Currently waiting for data</h4>
<p>The statistics system has not received any data from this host. Please make certain the Longview agent is installed, correctly configured, and running.</p>

app/views/hosts/add.html.erb
<%= form_tag do_add_host_path, class: "form-horizontal" do %>
<div class="row">
  <div class="col-md-12">
    <h3>Add New Host</h3>
    <div class="form-group">
      <label class="control-label col-md-2" for="host_name">Name:</label>
      <div class="col-md-10">
        <%= text_field_tag "host[name]", params["host[name]"], class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-2" for="host[active]">Active:</label>
      <div class="col-md-2">
        <%= select_tag "host[active]", options_for_select([['Active', 1], ['Inactive', 0]], 1), class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-2" for="host[interval]">Update Interval:</label>
      <div class="col-md-2">
        <div class="input-group">
        <%= text_field_tag "host[interval]", 10, {class: "form-control", type: "number", min: 10, max: 6000} %>
        <span class="input-group-addon"> seconds</span>
        </div>
      </div>
    </div>
    <div class="text-right">
      <%= hidden_field_tag "host[id]", @api_key %>
      <%= submit_tag "Save", class: "btn btn-primary" %>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="well">
      <dl>
        <dt>Host API Key</dt>
        <dd><%= @api_key %></dd>
      </dl>
      <p>This API key is placed in the keyfile on the server and identifies the host when it attempts to connect to the Deep Vision server. Hosts without a key will not be able to store usage statistics.</p>
    </div>
  </div>
</div>
<% end %>

app/views/hosts/disks.html.erb
<% if @instant.nil? %>
<%= render "waiting" %>
<% else %>

<h3>Disks</h3>
<% @disks.each do |key| %>
<div class="row">
  <div class="col-md-3">
    <h4><%= key %></h4>
  </div>
  <%
    id_key = key.dup
    id_key.gsub!("/", "")
  %>
  <div class="col-md-9">
    <div id="<%= id_key %>-flot" data-flot-height="250"></div>
    <div id="<%= id_key %>-flot-legend"></div>
  </div>
</div>
<% end %>
<% end %>

app/views/hosts/network.html.erb
<% if @instant.nil? %>
<%= render "waiting" %>
<% else %>

<h3>Network</h3>

<% @network_interfaces.each do |key| %>
<div class="row">
  <div class="col-md-3">
    <h4><%= key %></h4>
  </div>
  <div class="col-md-9">
    <div id="<%= key %>-flot" data-flot-height="250"></div>
    <div id="<%= key %>-flot-legend"></div>
  </div>
</div>
<% end %>
<% end %>

app/views/hosts/overview.html.erb
<% if @instant.nil? %>
<%= render "waiting" %>
<% else %>
<div class="row">
  <div class="col-md-8">
    <h3 class="name"><%= @host["name"] %></h3>
  </div>
  <div class="col-md-4 text-right">
    <%= select_tag 'date_range', options_for_select([['Past 30 Minutes', 1], ['Past 24 Hours', 2], ['Past 7 Days', 3], ['Past 30 Days', 4], ['Past Year', 5]], @range) %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h4>CPU</h4>
    <div id="cpu-flot" data-flot-height="300"></div>

    <h4>Memory</h4>
    <div id="memory-flot" data-flot-height="300"></div>
    <div id="memory-flot-legend"></div>
  </div>
  <div class="col-md-4">
    <div class="well">
      <p class="hostname"><%= @instant["SysInfo.hostname"] %></p>
      <ul>
        <li><%= @instant["SysInfo.os.dist"]%> <%= @instant["SysInfo.os.distversion"]%> (<%= @instant["SysInfo.kernel"] %>)</li>
        <li><%= @instant["SysInfo.cpu.type"] %></li>
        <li>Uptime <%= distance_of_time_in_words_to_now Time.at(Time.now.to_i - @instant["Uptime"].to_i) %></li>
      </ul>
    </div>
    <h5>Load</h5>
    <div id="load-flot" data-flot-height="120"></div>
    <h5>Network</h5>
    <div id="network-flot" data-flot-height="120"></div>
    <div id="network-flot-legend"></div>
    <h5>Disk IO</h5>
    <div id="disk-flot" data-flot-height="120"><%= debug @disk_reads %></div>
    <div id="disk-flot-legend"></div>
  </div>
</div>
<% end %>

app/views/hosts/processes.html.erb
<% if @processes.nil? %>
<%= render "waiting" %>
<% else %>

<h4>Processes</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Process</th>
      <th>User</th>
      <th>Count</th>
    </tr>
  </thead>
  <% 
  @process_keys = @processes.keys.sort
  @process_keys.each do |key|
    count = @processes[key]
    process_array = key.split(".")
    process_name = process_array[1]
    process_user = process_array[2]
  %>
    <tr>
      <td><%= process_name %></td>
      <td><%= process_user %></td>
      <td><%= count %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/hosts/settings.html.erb
<%= form_tag nil, class: "form-horizontal" do %>
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <label class="control-label col-md-2" for="host_name">Name:</label>
      <div class="col-md-10">
        <input type="text" class="form-control" name="host[name]" value="<%= @host["name"] %>">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-2" for="host[active]">Active:</label>
      <div class="col-md-2">
        <%= select_tag "host[active]", options_for_select([['Active', 1], ['Inactive', 0]], @host["active"]), class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-2" for="host[interval]">Update Interval:</label>
      <div class="col-md-2">
        <div class="input-group">
        <%= text_field_tag "host[interval]", ((@host["interval"].nil?) ? 10 : @host["interval"]), {class: "form-control", type: "number", min: 10, max: 6000} %>
        <span class="input-group-addon"> seconds</span>
        </div>
      </div>
    </div>
    <div class="text-right">
      <%= submit_tag "Save", class: "btn btn-primary" %>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="well">
      <dl>
        <dt>Host API Key</dt>
        <dd><%= @host["id"] %></dd>
      </dl>
      <p>This API key is placed in the keyfile on the server and identifies the host when it attempts to connect to the Deep Vision server. Hosts without a key will not be able to store usage statistics.</p>
    </div>
  </div>
</div>
<% end %>

app/views/hosts/system.html.erb
<% if @instant.nil? %>
<%= render "waiting" %>
<% else %>
<div class="row">
  <div class="col-md-4">
    
    <h4><%= @instant["SysInfo.hostname"] %></h4>
    <ul>
      <li><%= @instant["SysInfo.os.dist"]%> <%= @instant["SysInfo.os.distversion"]%> (<%= @instant["SysInfo.kernel"] %>)</li>
      <li><%= @instant["SysInfo.cpu.type"] %></li>
      <li>Uptime <%= distance_of_time_in_words_to_now Time.at(Time.now.to_i - @instant["Uptime"].to_i) %></li>
    </ul>
  </div>
  <div class="col-md-4">
    <h4>CPU</h4>
    <ul>
      <li><%= @instant["SysInfo.cpu.type"] %></li>
      <li><%= @instant["SysInfo.cpu.cores"] %> cores</li>
    </ul>
  </div>
  <div class="col-md-4">
    <h4>Memory</h4>
    <ul>
      <li><%= @longterm["Memory.real.used"] + @longterm["Memory.real.free"] %> bytes real</li>
      <li><%= @longterm["Memory.swap.used"] + @longterm["Memory.swap.free"] %> bytes swap</li>
    </ul>
  </div>
</div>

<h4>Listening Services</h4>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Process</th>
          <th>User</th>
          <th>Protocol</th>
          <th>Port</th>
          <th>IP Address</th>
        </tr>
      </thead>
      <% 
      @instant["Ports.listening"].sort_by! {|h| h["name"]}
      @instant["Ports.listening"].each do |listener| 
        if listener["name"] != "master"
      %>
      <tr>
        <td><%= listener["name"] %></td>
        <td><%= listener["user"] %></td>
        <td><%= listener["type"] %></td>
        <td><%= listener["port"] %></td>
        <td><%= listener["ip"] %></td>
      </tr>
      <% end
      end %>
    </table>
  </div>
</div>
<% end %>