config/routes.rb
Deepvision::Application.routes.draw do

  root 'dashboard#index'

  mount Longview::API => "/endpoint"

  get 'hosts/:id/overview' => 'hosts#overview', as: :overview
  get 'hosts/:id/network' => 'hosts#network', as: :network
  get 'hosts/:id/disks' => 'hosts#disks', as: :disks
  get 'hosts/:id/processes' => 'hosts#processes', as: :processes
  get 'hosts/:id/system' => 'hosts#system', as: :system
  get 'hosts/:id/settings' => 'hosts#settings', as: :settings
  post 'hosts/:id/settings' => 'hosts#settings', as: :settings_save

  get 'hosts/add' => 'hosts#add', as: :add_host
  post 'hosts/add' => 'hosts#do_add', as: :do_add_host

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Deepvision" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= include_gon %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-lg-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <div class="navbar-collapse collapse navbar-lg-collapse">
        <% if @dashboard %>
          <div class="row">
            <div class="col-md-6">
              <ul class="nav navbar-nav" id="select-metric">
                <li id="cpu-toggle" data-stat="cpu" class="active"><%= link_to "CPU", "#" %></li>
                <li id="memory-toggle" data-stat="memory" ><%= link_to "Memory", "#"  %></li>
                <li id="swap-toggle" data-stat="swap" ><%= link_to "Swap", "#"  %></li>
                <li id="load-toggle" data-stat="load" ><%= link_to "Load", "#"  %></li>
                <li id="network-toggle" data-stat="network" ><%= link_to "Network", "#"  %></li>
              </ul>
            </div>
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-8">
                <ul class="nav navbar-nav navbar-left">
                  <li id="sort-name"><%= link_to "Name", "#" %></li>
                  <li id="sort-metric" class="active"><%= link_to "Metric", "#"  %></li>
                  <li id="sort-asc" class="sort-direction active"><%= link_to "#" do%><i class="icon-arrow-up"></i><% end %></li>
                  <li id="sort-desc" class="sort-direction"><%= link_to "#" do%><i class="icon-arrow-down"></i><% end %></li>
                  <li id="host-add"><%= link_to add_host_path do %><i class="icon-plus-sign-alt"></i><% end %></li>
                </ul>
                </div>
                <div class="col-md-4">
                <div class="navbar-form navbar-right">
                  <input id="quick_search" class="form-control" placeholder="Search">
                </div>
                </div>
              </div>
            </div>



          </div>


        <% elsif @add_host %>
          <ul class="nav navbar-nav auto-width">
            <li>
              <%= link_to root_path do %>
                <i class="icon-double-angle-left"></i> Dashboard
              <% end %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav auto-width">
            <li>
              <%= link_to root_path do %>
                <i class="icon-double-angle-left"></i> Dashboard
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav auto-width">
            <li class="<%= 'active' if params[:action] == "overview" %>">
              <%= link_to "Overview", overview_path(@host["id"]) %>
            </li>
            <li class="<%= 'active' if params[:action] == "network" %>">
              <%= link_to "Network", network_path(@host["id"]) %>
            </li>
            <li class="<%= 'active' if params[:action] == "disks" %>">
              <%= link_to "Disks", disks_path(@host["id"]) %>
            </li>
            <li class="<%= 'active' if params[:action] == "processes" %>">
              <%= link_to "Processes", processes_path(@host["id"]) %>
            </li>
            <li class="<%= 'active' if params[:action] == "system" %>">
              <%= link_to "System", system_path(@host["id"]) %>
            </li>
            <li class="<%= 'active' if params[:action] == "settings" %>">
              <%= link_to "Settings", settings_path(@host["id"]) %>
            </li>
          </ul>
        <% end %>
        </div>
        
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h5>Deep Vision</h5>
            <p>Open source resource monitoring and alerting.</p>
          </div>
          <div class="col-lg-6 text-right">
            <p>Authored by Eric Perkins. Follow me on <a href="http://twitter.com/enperkins" target="_blank">Twitter</a>.</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>